DISPATCH-1720, DISPATCH-1739: move console tests + lint check jobs into the main 'build' workflow, add a RAT check job
This closes #813

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -197,3 +197,54 @@ jobs:
           name: cores_${{matrix.os}}_${{matrix.buildType}}_${{matrix.runtimeCheck}}_${{matrix.shard}}
           path: |
             **/core
+
+  console-test:
+    name: Console Tests
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install Dependencies
+        run: cd console/react && npm ci
+
+      - name: Run Tests
+        run: cd console/react && npm run test
+
+  console-eslint:
+    name: Console ESLint
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+
+      - name: Install Dependencies
+        run: cd console/react && npm ci
+
+      - name: Install Typescript
+        run: cd console/react && npm install typescript
+
+      - name: Run ESLint
+        run: cd console/react && npx eslint --max-warnings 0 .
+
+  rat_check:
+    name: RAT Check
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - uses: actions/cache@v2
+        with:
+          path: ~/.m2/repository
+          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
+          restore-keys: |
+            ${{ runner.os }}-maven-
+
+      - name: Install JDK ${{ matrix.java }}
+        uses: actions/setup-java@v1
+        with:
+          java-version: 11
+
+      - name: RAT Check
+        run: mvn apache-rat:check
+
+      - name: Output
+        if: ${{ ! cancelled() }}
+        run: cat target/rat.txt || echo "Unable to print output"
